aws/aws-encryption-sdk-java

CHANGELOG.md, README.md, pom.xml, src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java, src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
Restoring these for now due to concerns about compatibility with relaxing this
restriction.
=> Restore frame size alignment checks

.travis.yml
* Disable quiet mode for detailed log information
* Explicitly specify the OS environment in use
=> Updating travis configuration

.travis.yml
Please wait for the travis build to pass before merging.
=> Start testing on java 9

CHANGELOG.md, README.md, pom.xml
Modify version numbers to version 1.3.2 for new release
=> 1.3.2 release

.travis.yml, pom.xml
=> Update Mockito and add CI for JDK9/10/11

CHANGELOG.md, README.md, pom.xml
Add a date to the changelog with the release date for 1.3.6
=> Add date for 1.3.6 release

pom.xml
n/a
latest version of Mockito
[yes]
=> mockito 2.23.4

pom.xml
n/a
latest version of BouncyCastle library
[yes]
=> bouncycastle 1.60

CHANGELOG.md, README.md, pom.xml
Various changes to release 1.4.0 version.
=> Update versions for 1.4.0

pom.xml
*Issue #, if available:* #123
Move to new sonatype endpoint
This does not require any changes by our consumers.
It is solely a publishing change.
=> Move to new sonatype endpoint. #123

src/main/java/com/amazonaws/encryptionsdk/internal/AesGcmJceKeyCipher.java, src/main/java/com/amazonaws/encryptionsdk/internal/JceKeyCipher.java, src/main/java/com/amazonaws/encryptionsdk/internal/RsaJceKeyCipher.java, src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/MasterKeyProviderKeyring.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/RawAesKeyring.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/RawKeyring.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/RawRsaKeyring.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/StandardKeyrings.java, src/test/java/com/amazonaws/encryptionsdk/keyrings/MasterKeyProviderKeyringTest.java, src/test/java/com/amazonaws/encryptionsdk/keyrings/RawKeyringTest.java, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This change contains the initial implementation of the MasterKeyProvider Keyring.
=> Define the MasterKeyProvider Keyring.

src/examples/java/com/amazonaws/crypto/examples/datakeycaching/LambdaDecryptAndWriteExample.java
Lambda (AFAIK) requires a no-argument constructor to work. Additionally, by storing the cache in a `static final` field, we ensure that all invocations in a given Lambda instance properly use the cache. The example still has the custom constructors to make it easier to experiment with.
=> Have Lambda example cache data keys in a static field.

src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/custom/RequiringEncryptionContextFields.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/CustomClientSupplier.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/CustomKmsClientConfig.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecrypt.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecryptInRegionOnly.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecryptWithPreferredRegions.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/MultipleRegions.java, src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/SingleCmk.java, src/examples/java/com/amazonaws/crypto/examples/keyring/multi/AwsKmsWithEscrow.java, src/examples/java/com/amazonaws/crypto/examples/legacy/BasicEncryptionExample.java, src/examples/java/com/amazonaws/crypto/examples/legacy/EscrowedEncryptExample.java, src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/DiscoveryDecrypt.java, src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/MultipleRegions.java, src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/SingleCmk.java, src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/multi/AwsKmsWithEscrow.java
*Issue #, if available:* #176
Replacing KMS usage with AWS KMS.
=> Replace KMS with AWS KMS

CONTRIBUTING.md, README.md
*Description of changes:* Add CONTRIBUTING.md with security issue notifications section and link to README.md for discoverability.
=> Add CONTRIBUTING.md and link security issue notifications to README.md

README.md, pom.xml
Updating version for 1.6.2 release
=> Updating version for 1.6.2 release

src/examples/java/com/amazonaws/crypto/examples/legacy/MultiRegionRecordPusherExample.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyring.java, src/main/java/com/amazonaws/encryptionsdk/keyrings/StandardKeyrings.java, src/test/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyringTest.java
*Issue #, if available:* Fixes #198
*Description of changes:* Pulling this into own change so that future multikeyring PR will be easier to review.
=> Rename childrenKeyrings to childKeyrings in MultiKeyring

src/main/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyring.java, src/test/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyringTest.java
*Issue #, if available:* #201 
=> refactor!: Update multikeyring generator to require generating keys

README.md
* Updating the README for 2.0.0
=> chore: Update README for 2.0.0

src/test/java/com/amazonaws/encryptionsdk/CommitmentKnownAnswerTest.java
* Adding TAG_INTEGRATION to KAT tests
* Merge master into keyrings (1 README commit)
=> chore: add TAG_INTEGRATION to KAT tests

buildspec.yml, codebuild/corretto11.yml, codebuild/corretto8.yml, codebuild/openjdk11.yml, codebuild/openjdk8.yml
Adding buildspec to batch build
multiple JDK environments
* corretto8
* corretto11
* openjdk8
* openjdk11
=> chore: Add AWS CodeBuild buildspec

CHANGELOG.md, README.md, pom.xml
*Description of changes:* bump version, update changelog for v2.3.1
=> chore: bump version, update changelog for v2.3.1

CHANGELOG.md, README.md, pom.xml
=> bump version,  update changelog for v2.3.2

pom.xml, src/test/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProviderTest.java
=> chore: Upgrade mockito to 4.0.0

.github/dependabot.yml
Update dependabot config to also update mainline-1.x.
[Link](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#target-branch) on how to configure it
=> chore: update dependabot to update mainline-1.x

pom.xml, src/test/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProviderTest.java
=> chore: Upgrade mockito to 4.2.0

codebuild/release/upload_artifacts.yml
*Issue #, if available:* Wrong branch in upload_artifacts
*Description of changes:* Correct branch in upload_artifacts
=> fix: correct branch in upload_artifacts

src/test/java/com/amazonaws/encryptionsdk/internal/DecryptionHandlerTest.java
=> chore(ci): add missing @Test annotation

NOTICE.txt
=> fix: NOTICE.txt

codebuild/release/version.yml
=> chore: update node version in versioning cb step

.releaserc, codebuild/release/upload_artifacts.yml
- Update release script to populate date in our semantic commit messages.
- Issue Commit: [AWS Encryption SDK 2.4.1 Release -- $(date +%Y-%m-%d)](https://github.com/aws/aws-encryption-sdk-java/commit/03b346fd1ea67aa219714638ac1024c2cd8f1c84)
=> chore: fix release script

cfn/ci_cd.yml
=> chore(CFN): remove unused policy

pom.xml
=> chore(deps): bump bcprov-jdk18on from 1.77 to 1.78.1
