aws/aws-encryption-sdk-java

- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
estimateCiphertextSize was not passing a plaintext size down to the CMM, so the
caching CMM assumed that a streaming encryption of unknown size was being
performed, and bypassed the cache entirely.
This change passes a plaintext size of zero instead to allow cached keys to be
used; since we don't actually encrypt any data it's safe to not consume any of
the byte limit.
Note that this may not behave quite right if the CMM does more clever things
with plaintext size. In general we should probably resolve this by moving
estimateCiphertextSize over to the Cipher*Stream objects instead, where it can
know the actual DataKeys in use instead of hoping they're reasonably
consistently sized.
Fixes: #29
> Make estimateCiphertextSize work with cached keys

- .gitignore
- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKey.java
- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
The previously method to append user-agent information (`request.getRequestClientOptions().appendUserAgent()`) really is an internal method and we should avoid using it if possible. Now that `ClientConfiguration` supports `withUserAgentSuffix()`, we're switching to it.
Modification to .gitignore is to help it work better in my workspace.
> Switch to supported ClientConfiguration.withUserAgentSuffix

- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
- src/test/java/com/amazonaws/encryptionsdk/CryptoInputStreamTest.java
- src/test/java/com/amazonaws/encryptionsdk/CryptoOutputStreamTest.java
- src/test/java/com/amazonaws/encryptionsdk/TestUtils.java
Issue #42
The purpose of this is to remove unneeded frame-size restriction on encrypt. Decrypt has never enforced these restrictions. (So ciphertexts created by this new version will be decryptable by all old versions as well, even in other languages.)
All tests pass on my development box.
> Remove frame-size restrictions.

- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKey.java
- src/test/java/com/amazonaws/services/kms/KMSProviderBuilderIntegrationTests.java
- src/test/java/com/amazonaws/services/kms/KMSProviderBuilderMockTests.java
- src/test/java/com/amazonaws/services/kms/LegacyKMSMasterKeyProviderTests.java
The logic to set the UA suffix to include the SDK version was dropped as part of the new builder refactoring. This change restores it.
Also included is a minor fix to a test (this didn't break anything but should be fixed out of general tidiness).
> Restore logic to set UA suffixes

- src/test/java/com/amazonaws/encryptionsdk/internal/FrameEncryptionHandlerVeryLongTest.java
This test is currently failing (and only runs when attempting release to Maven). The problem is that the library rejects the frame with a maximum index unless it is also a final frame. This fixes that.
> Fix FrameEncryptionHandlerVeryLongTest so that last frame is final.

- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
Move to using RegionUtils.getRegion instead of Region.getRegion(Regions.fromName()).
This is the recommended approach from the AWS SDK team.
> Move to using RegionUtils.getRegion

- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
- src/test/java/com/amazonaws/services/kms/KMSProviderBuilderMockTests.java
- src/test/java/com/amazonaws/services/kms/MockKMSClient.java
The default region was not actually being consulted when presented with a
regionless key ID (such as a bare UUID or an "alias/foo" value). Fixes #50.
> Fix bare aliases not using default region

- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
This is to fix #56 
I have manually verified that all existing tests pass as well as manual verification that a logged warning appears if and only if an unsupported algorithm is used with `JceMasterKey`.
> Log a warning when an unsupported asym algorithm is used with JceMasterKey

- CHANGELOG.md
- README.md
- pom.xml
Description of changes: Documentation changes to update hyperlinks, and minor version bump.
> Move repository from awslabs to aws.

- .gitignore
- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/internal/StaticMasterKey.java
- src/test/java/com/amazonaws/encryptionsdk/jce/JceMasterKeyTest.java
Algorithm names in the JCA spec are not case-sensitive. This makes
JceMasterKey algorithm names case insensitive.
> Make JceMasterKey Case Insensitive

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKey.java
- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/IntegrationTestSuite.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSProviderBuilderIntegrationTests.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSProviderBuilderMockTests.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSTestFixtures.java
- src/test/java/com/amazonaws/encryptionsdk/kms/LegacyKMSMasterKeyProviderTests.java
- src/test/java/com/amazonaws/encryptionsdk/kms/MockKMSClient.java
- src/test/java/com/amazonaws/encryptionsdk/kms/XCompatKmsDecryptTest.java
We now verify that the requested region is reachable before caching the KMS
client. Behavior verified by tests (for the should-not-cache case) and log inspection (for the should-cache case).
> Restore KMS caching logic

- README-JML.md
- src/main/java/com/amazonaws/encryptionsdk/EncryptedDataKey.java
- src/main/java/com/amazonaws/encryptionsdk/exception/.gitignore
- src/main/java/com/amazonaws/encryptionsdk/exception/AwsCryptoException.java
- src/main/java/com/amazonaws/encryptionsdk/exception/BadCiphertextException.java
- src/main/java/com/amazonaws/encryptionsdk/exception/CannotUnwrapDataKeyException.java
- src/main/java/com/amazonaws/encryptionsdk/exception/NoSuchMasterKeyException.java
- src/main/java/com/amazonaws/encryptionsdk/exception/ParseException.java
- src/main/java/com/amazonaws/encryptionsdk/exception/UnsupportedProviderException.java
- src/main/java/com/amazonaws/encryptionsdk/internal/PrimitivesParser.java
- src/main/java/com/amazonaws/encryptionsdk/model/KeyBlob.java
N/A
These changes add JML (Java Modeling Language) formal specifications to several files that have been verified using OpenJML (https://github.com/OpenJML/OpenJML). Included also is a README-JML file that gives a summary of the semantics of JML (with a short summary at the top). From the perspective of the Java compiler, JML annotations are all comments, so annotations should not force changes to ordinary code.
The files annotated in this request were meant to be those needed to ensure a specification for KeyBlob could verify. The following is a listing:
* the exceptions in encryptionsdk.exception
* encryptionsdk.internal.PrimitivesParser
* encryptionsdk.EncryptionDataKey
* encryptionsdk.model.KeyBlob
All the annotations verify (i.e., …
> JML Specifications for KeyBlob

- src/main/java/com/amazonaws/encryptionsdk/model/DecryptionMaterialsRequest.java
- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/model/DecryptionMaterialsRequestTest.java
Bug fix, where a builder had copied one field twice and omitted the copy of another field.
> Bug fix, model.DecryptionMaterialsRequest.Builder

- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/DefaultCryptoMaterialsManager.java
- src/main/java/com/amazonaws/encryptionsdk/caching/CachingCryptoMaterialsManager.java
- src/main/java/com/amazonaws/encryptionsdk/internal/BlockEncryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Constants.java
- src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/FrameEncryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/main/java/com/amazonaws/encryptionsdk/internal/VersionInfo.java
- src/main/java/com/amazonaws/encryptionsdk/model/CipherFrameHeaders.java
- src/main/java/com/amazonaws/encryptionsdk/model/CiphertextType.java
- src/test/java/com/amazonaws/encryptionsdk/UtilsTest.java
- src/test/java/com/amazonaws/encryptionsdk/caching/CacheIdentifierTests.java
- src/test/java/com/amazonaws/encryptionsdk/caching/LocalCryptoMaterialsCacheTest.java
- src/test/java/com/amazonaws/encryptionsdk/caching/NullCryptoMaterialsCacheTest.java
Update Compiler and Surefire Plugin
Basic Java cleanup 
> Minor java code cleanup

- src/main/java/com/amazonaws/encryptionsdk/internal/EncryptionContextSerializer.java
Fixed typos in exception messages (excryption -> encryption)
> Fixed typos in exception messages

- src/main/java/com/amazonaws/encryptionsdk/model/CipherBlockHeaders.java
n/a
Included are JML specifications for CipherBlockHeaders, which verify by running the development build of OpenJML. 
A pertinent issue for review might be the specification for `deserialize()` since the partial deserialization behavior is difficult to concisely state in JML; is there a simpler property that could be stated of the function and applied similarly to the other partial deserializations in the models package?
> JML Specifications for CipherBlockHeaders

- src/main/java/com/amazonaws/encryptionsdk/CryptoAlgorithm.java
- src/main/java/com/amazonaws/encryptionsdk/internal/BouncyCastleConfiguration.java
- src/main/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithm.java
This avoids issues where a shaded version of BCProvider is installed in the
system JCE provider list, which can result in problems when we pass an
ECNamedCurveParameterSpec from a different shaded version of BC.
Fixes: #68
> Use the BouncyCastleProvider class directly

- pom.xml
In the upgrade to maven javadoc 3.0.0, the parameter to ignore doc linting
changed. This means that javadoc fails to build. This updates the parameter to
the correct one for disabling linting.
> Update parameter to disable doc linting

- README.md
Previously, it wasn't clear whether Java 8 was recommended or required. This
makes it clear that Java 8 is the minimum supported version.
> Update README to state that Java 8 or higher is required

- src/main/java/com/amazonaws/encryptionsdk/CryptoAlgorithm.java
- src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithm.java
- src/test/java/com/amazonaws/encryptionsdk/DefaultCryptoMaterialsManagerTest.java
- src/test/java/com/amazonaws/encryptionsdk/jce/KeyStoreProviderTest.java
This makes it so that we don't explicitly use BouncyCastle for crypto except when necessary. Exceptions include:
* KeyGeneration (for easy serialization of compressed points)
* RSA-OAEP (as the default java implementation is non-standard)
I have run multiple tests locally including verifying that installing custom providers at high priority still work.
> Remove explicit BC usage when not necessary

- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/MasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/internal/CryptoHandler.java
- src/main/java/com/amazonaws/encryptionsdk/model/CiphertextHeaders.java
In addition to some bad JavaDoc comments this informs the JavaDoc plugin
of our source version to avoid other errors.
Manually ran `mvn clean javadoc:javadoc` and saw that it now completes successfully (and it didn't before).
> Fix broken javadoc

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/internal/EncryptionContextSerializer.java
- src/main/java/com/amazonaws/encryptionsdk/internal/FrameEncryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/test/java/com/amazonaws/encryptionsdk/internal/FrameEncryptionHandlerVeryLongTest.java
Java 9 introduced a change in ByteBuffers causing some methods to fail
when compiled with Java 9 (or newer) but executed on Java 8 (or older)
regardless of compatability levels applied.
See https://github.com/mongodb/mongo-java-driver/commit/21c91bd364d38489e0bbe2e390efdb3746ee3fff
> Version 1.4.1 uses ByteBuffers in a backwards compatible way.

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
- src/main/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithm.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
- src/test/java/com/amazonaws/encryptionsdk/XCompatDecryptTest.java
- src/test/java/com/amazonaws/encryptionsdk/caching/CacheIdentifierTests.java
- src/test/java/com/amazonaws/encryptionsdk/internal/StaticMasterKey.java
- src/test/java/com/amazonaws/encryptionsdk/model/ByteFormatCheckValues.java
* This change switches Base64 codec from java.util.Base64 to Base64 from Apache Commons Codec. This is to enable use of this library on systems that do not contain java.util.Base64 but do support other Java 8 features.
* Upgrade dependencies to their most recent versions.
* Bump version to 1.5.0
* `mvn verify` passes on my laptop and runs AllTestsSuite with its 5726 tests.
* Travis CI tests pass.
> Switch Base64 codec, upgrade dependencies, and bump version to 1.5.0

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
- src/main/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithm.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
- src/test/java/com/amazonaws/encryptionsdk/UtilsTest.java
- src/test/java/com/amazonaws/encryptionsdk/XCompatDecryptTest.java
- src/test/java/com/amazonaws/encryptionsdk/caching/CacheIdentifierTests.java
- src/test/java/com/amazonaws/encryptionsdk/internal/StaticMasterKey.java
- src/test/java/com/amazonaws/encryptionsdk/model/ByteFormatCheckValues.java
Turns out adding a dependency on Apache Commons Codec is not a good idea so we'll use Base64 codec from BouncyCastle for now. I've added utility methods for Base64 encoding/decoding so the next time we change Base64 codec we can make the change in one place.
* `mvn clean install` passes
> Remove dependency on Commons Codec, use Base64 codec in BouncyCastle, bump version to 1.6.0

- .travis.yml
- CHANGELOG.md
- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/NewCompatTest.java
- src/test/java/com/amazonaws/encryptionsdk/TestVectorRunner.java
Now handles standard test vectors when the ZIP containing them is
pointed to by the testVectorZip system property.
Example:
`mvn install -Dgpg.skip=true '-DtestVectorZip=https://github.com/awslabs/aws-encryption-sdk-test-vectors/raw/master/vectors/awses-decrypt/python-1.3.8.zip'`
This also adds them to our standard travis build.
> Add support for standard test vectors.

- CHANGELOG.md
- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
*Issue #, if available:* #41 
Removes explicit use of BouncyCastle from the `JceMasterKey`. The concern and complexity here is that the default Java provider implements RSA-OAEP in an incompatible way. By using `OAEPParameterSpec` explicitly, we can work around the incompatibility in all cases.
> Remove use of BouncyCastle from JceMasterKey

- CHANGELOG.md
- src/main/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithm.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/test/java/com/amazonaws/encryptionsdk/TestUtils.java
- src/test/java/com/amazonaws/encryptionsdk/UtilsTest.java
- src/test/java/com/amazonaws/encryptionsdk/internal/TrailingSignatureAlgorithmTest.java
*Issue #, if available:* #41
Removes explicit use of BouncyCastle from the `ECDSASignatureAlgorithm` implementation of `TrailingSignatureAlgorithm`.
> Remove use of BouncyCastle for EC key generation and point (de)compression

- src/main/java/com/amazonaws/encryptionsdk/CryptoAlgorithm.java
- src/main/java/com/amazonaws/encryptionsdk/internal/HmacKeyDerivationFunction.java
- src/test/java/com/amazonaws/encryptionsdk/internal/HmacKeyDerivationFunctionTest.java
*Issue #, if available:* #41
Removes explicit use of BouncyCastle for deriving an HMAC in `CryptoAlgorithm`.
> Remove use of BouncyCastle for HMAC key derivation

- pom.xml
- src/examples/java/com/amazonaws/crypto/examples/BasicEncryptionExample.java
- src/test/java/com/amazonaws/crypto/examples/BasicEncryptionExampleTest.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSTestFixtures.java
*Issue #, if available:* #108
Add a basic example for encrypting and decrypting with a KMS CMK.
> Add a basic example for encrypting and decrypting with a KMS CMK

- CHANGELOG.md
- README.md
- pom.xml
> Update docs in prep for 1.6.1

- pom.xml
Newer versions of gpg fail signing with the following error message:
`gpg: signing failed: Inappropriate ioctl for device`
This can be fixed by explicitly telling gpg to ask the caller for the passphrase/pin, rather than letting to attempt to query for it out of band to a human directly (which doesn't exist). On the command line it is done by adding the arguments `--pinentry-mode loopback`. This change tells maven to pass in these new arguments.
This has been tested with as part of building, signing and releasing version 1.6.1 of the aws-encryption-sdk-java.
> Fix for new versions of gpg

- src/main/java/com/amazonaws/encryptionsdk/keyrings/KeyringTrace.java
- src/main/java/com/amazonaws/encryptionsdk/keyrings/KeyringTraceEntry.java
- src/main/java/com/amazonaws/encryptionsdk/keyrings/KeyringTraceFlag.java
- src/main/java/com/amazonaws/encryptionsdk/model/DecryptionMaterials.java
- src/main/java/com/amazonaws/encryptionsdk/model/EncryptionMaterials.java
- src/test/java/com/amazonaws/encryptionsdk/keyrings/KeyringTraceTest.java
*Issue #, if available:* #102
Creating a keyring trace and adding to encryption and decryption materials to allow for auditing actions a keyring has taken on encryption materials.
> Create keyring trace and add to encryption and decryption materials.

- src/main/java/com/amazonaws/encryptionsdk/internal/AesGcmJceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/JceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/RsaJceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
- src/test/java/com/amazonaws/encryptionsdk/UtilsTest.java
*Issue #, if available:* #102
In anticipation of the RawAesKeyring and RawRsaKeyring needing logic currently embedded in the JceMasterKey, this change extracts that logic into the JceKeyCipher class so it may be shared.
> Refactor JceMasterKey to extract logic to be shared by raw keyrings.

- CHANGELOG.md
- README.md
- pom.xml
- src/examples/java/com/amazonaws/crypto/examples/BasicEncryptionExample.java
- src/main/java/com/amazonaws/encryptionsdk/internal/AesGcmJceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/JceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/RsaJceKeyCipher.java
- src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java
- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
- src/test/java/com/amazonaws/crypto/examples/BasicEncryptionExampleTest.java
- src/test/java/com/amazonaws/encryptionsdk/UtilsTest.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSTestFixtures.java
Merge head of master into keyring
> Merge head of master into keyring

- src/main/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyring.java
- src/main/java/com/amazonaws/encryptionsdk/keyrings/StandardKeyrings.java
- src/test/java/com/amazonaws/encryptionsdk/keyrings/MultiKeyringTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
This change contains the initial implementation of the Multi Keyring.
> Define the MultiKeyring

- pom.xml
- src/examples/java/com/amazonaws/crypto/examples/BasicEncryptionExample.java
- src/examples/java/com/amazonaws/crypto/examples/EscrowedEncryptExample.java
- src/examples/java/com/amazonaws/crypto/examples/FileStreamingExample.java
- src/examples/java/com/amazonaws/crypto/examples/RawAesKeyringExample.java
- src/examples/java/com/amazonaws/crypto/examples/RawRsaKeyringDecryptExample.java
- src/examples/java/com/amazonaws/crypto/examples/RawRsaKeyringEncryptExample.java
- src/examples/java/com/amazonaws/crypto/examples/datakeycaching/LambdaDecryptAndWriteExample.java
- src/examples/java/com/amazonaws/crypto/examples/datakeycaching/MultiRegionRecordPusherExample.java
- src/test/java/com/amazonaws/crypto/examples/RawAesKeyringExampleTest.java
- src/test/java/com/amazonaws/crypto/examples/RawRsaKeyringDecryptExampleTest.java
- src/test/java/com/amazonaws/crypto/examples/RawRsaKeyringEncryptExampleTest.java
Adding example code for Keyrings, as well as updating and adding the data key caching example code from the Documentation.
> Additional example code for Keyrings

- README.md
Updating the Readme for Keyrings and paring down the verbiage to match the other ESDKs
> Update Readme for Keyrings

- src/examples/java/com/amazonaws/crypto/examples/datakeycaching/SimpleDataKeyCachingExample.java
- src/test/java/com/amazonaws/crypto/examples/datakeycaching/SimpleDataKeyCachingExampleTest.java
Adding a simple example of data key caching
> Adding a simple example of data key caching

- src/examples/README.md
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/DiscoveryDecrypt.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/MultipleRegions.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/SingleCmk.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/multi/AwsKmsWithEscrow.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/rawaes/RawAes.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/rawrsa/RawRsa.java
To aid in migration efforts, these examples show the basics of how to use master key providers in the new example format.
> Add master key provider examples

- src/main/java/com/amazonaws/encryptionsdk/internal/FrameDecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/model/CiphertextHeaders.java
- src/test/java/com/amazonaws/encryptionsdk/internal/FrameDecryptionHandlerTest.java
- src/test/java/com/amazonaws/encryptionsdk/model/CiphertextHeadersTest.java
Add validation to ensure the length of the final frame in the final frame header does not exceed the frame size specified in the message header.
See https://github.com/aws/aws-encryption-sdk-javascript/pull/281
> fix: The final frame can not be larger than the Frame Length

- src/examples/README.md
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/caching/SimpleCache.java
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/custom/AlgorithmSuiteEnforcement.java
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/custom/RequiringEncryptionContextFields.java
Adds examples for using and creating CMMs.
> Add CMM examples

- README.md
The inline example in the readme is redundant now that we have 
more complete examples in the example directory.
> Remove inline example code from readme and reset version number

- CHANGELOG.md
Update changelog in preparation of version 1.7.0. The release date will be updated in a separate PR immediately before 1.7.0 is released.
> Updating changelog for version 1.7.0

- src/main/java/com/amazonaws/encryptionsdk/keyrings/RawRsaKeyring.java
- src/test/java/com/amazonaws/encryptionsdk/keyrings/RawRsaKeyringTest.java
Currently we rely on the JCE Cipher class to throw an exception when a user tries to encrypt with the RawRsaKeyring but has not configured a public key. The exception message does not obviously indicate what is wrong, so this change will explicitly check for a missing public key before attempting encryption and throw a more useful exception.
> Throw a more useful exception when trying to use the RawRsaKeyring to encrypt without a public key

- CHANGELOG.md
- pom.xml
Updating Bouncy Castle to the latest version (1.65)
> Update BouncyCastle to 1.65

- src/examples/java/com/amazonaws/crypto/examples/FileStreamingDefaults.java
- src/examples/java/com/amazonaws/crypto/examples/InMemoryStreamingDefaults.java
- src/examples/java/com/amazonaws/crypto/examples/OneStepDefaults.java
- src/examples/java/com/amazonaws/crypto/examples/OneStepUnsigned.java
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/caching/SimpleCache.java
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/custom/AlgorithmSuiteEnforcement.java
- src/examples/java/com/amazonaws/crypto/examples/cryptomaterialsmanager/custom/RequiringEncryptionContextFields.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/ActLikeAwsKmsMasterKeyProvider.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/CustomClientSupplier.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/CustomKmsClientConfig.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecrypt.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecryptInRegionOnly.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/DiscoveryDecryptWithPreferredRegions.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/MultipleRegions.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/awskms/SingleCmk.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/multi/AwsKmsWithEscrow.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/rawaes/RawAes.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/rawrsa/PublicPrivateKeySeparate.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/rawrsa/RawRsa.java
- src/examples/java/com/amazonaws/crypto/examples/keyring/rawrsa/RawRsaDerEncoded.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/DiscoveryDecrypt.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/MultipleRegions.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/SingleCmk.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/multi/AwsKmsWithEscrow.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/rawaes/RawAes.java
- src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/rawrsa/RawRsa.java
@MatthewBennington suggested this and I like it! We can't be too redundant about this. :)
> docs: add note in every example pointing out that encryption context is not secret

- pom.xml
https://github.com/aws/aws-encryption-sdk-java/issues/185
Update AWS Java SDK
> Update AWS Java SDK to version 1.11.704

- src/examples/README.md
In going through to enumerate the examples for https://github.com/awslabs/aws-encryption-sdk-specification/issues/103, I realized that the client supplier examples were not linked.
> docs: add links to custom AWS KMS client configuration examples in examples readme

- CHANGELOG.md
- src/main/java/com/amazonaws/encryptionsdk/internal/BlockDecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/FrameDecryptionHandler.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
- src/test/java/com/amazonaws/encryptionsdk/internal/BlockDecryptionHandlerTest.java
- src/test/java/com/amazonaws/encryptionsdk/internal/DecryptionHandlerTest.java
- src/test/java/com/amazonaws/encryptionsdk/internal/FrameDecryptionHandlerTest.java
Validate that the entire ciphertext has been processed before returning
> fix: validate entire ciphertext has been processed before returning

- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
*Description of changes:* We've seen confusion in other SDKs about this behavior. In Java we state pretty clearly this in the examples, but do not mention it directly in the KmsMasterKeyProvider docs. This fixes that.
> chore: Clarify KmsMasterKeyProvider Strict behavior in docs

- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/ParsedCiphertextTest.java
* Explicitly set a CommitmentPolicy in ParsedCiphertextTest in order to fix configuration conflict error when running the test.
* Add ParsedCiphertextTest to AllTestsSuite.
> test: fix ParsedCiphertextTest, add to AllTestsSuite

- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- codebuild/release/settings.xml
- codebuild/release/validate-prod.yml
- codebuild/release/validate-staging.yml
For now, these specs only deal with validation. However, I'm using the structure that includes a place for the release itself (currently a no-op) so that we can easily add that once we're ready.
Unlike in the Python ESDK, I made separate files for validation of prod vs staging releases, since the steps to hit the staging repository are a pretty big delta from hitting normal public repos.
*Testing:*
I've tested both the prod and release targets, including staging a version not on public maven to make extra sure that the staging validation is actually hitting the staging repository.
> chore: Add initial codebuild specs for automating release

- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- codebuild/release/settings.xml
This fills in the no-op steps to publish artifacts to either staging (i.e. CodeArtifact) or production (i.e. Sonatype).
*Testing:*
The staging workflow works completely with an existing release (if not already present on CodeArtifact), and the production workflow fails as expected because the latest version is already publicly released.
> chore: Automate staging and production release using CodeBuild as well

- .gitmodules
- CHANGELOG.md
- README.md
- codebuild/corretto11.yml
- codebuild/corretto8.yml
- codebuild/openjdk11.yml
- codebuild/openjdk8.yml
- pom.xml
- src/examples/java/com/amazonaws/crypto/examples/EscrowedEncryptExample.java
- src/examples/java/com/amazonaws/crypto/examples/FileStreamingExample.java
- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
- src/main/java/com/amazonaws/encryptionsdk/CryptoInputStream.java
- src/main/java/com/amazonaws/encryptionsdk/CryptoOutputStream.java
- src/main/java/com/amazonaws/encryptionsdk/DefaultCryptoMaterialsManager.java
- src/main/java/com/amazonaws/encryptionsdk/ParsedCiphertext.java
- src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/EncryptionHandler.java
- src/main/java/com/amazonaws/encryptionsdk/internal/SignaturePolicy.java
- src/main/java/com/amazonaws/encryptionsdk/internal/VersionInfo.java
- src/main/java/com/amazonaws/encryptionsdk/model/CiphertextHeaders.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoTest.java
- src/test/java/com/amazonaws/encryptionsdk/CryptoOutputStreamTest.java
- src/test/java/com/amazonaws/encryptionsdk/DecryptionMethod.java
- src/test/java/com/amazonaws/encryptionsdk/IntegrationTestSuite.java
- src/test/java/com/amazonaws/encryptionsdk/ParsedCiphertextTest.java
- src/test/java/com/amazonaws/encryptionsdk/TestVectorRunner.java
- src/test/java/com/amazonaws/encryptionsdk/internal/DecryptionHandlerTest.java
- src/test/java/com/amazonaws/encryptionsdk/internal/EncryptionHandlerTest.java
- src/test/java/com/amazonaws/encryptionsdk/kms/MaxEncryptedDataKeysIntegrationTest.java
- src/test/java/com/amazonaws/encryptionsdk/model/CiphertextHeadersTest.java
See https://github.com/aws/aws-encryption-sdk-java/security/advisories/GHSA-55xh-53m6-936r
> feat: Improvements to the message decryption process

- cfn/code_artifact.yml
- cfn/code_build_parameter_map.json
- cfn/prod-release.yml
code_artifact.yml and code_build_parameter_map.json are the same files that live in the [cfn](https://github.com/aws/private-aws-encryption-sdk-java-staging/tree/infra/cfn) branch of the private repos 
> chore: source controlling cfn templates that will be used for our release process

- cfn/ci_cd.yml
- cfn/prod-release.yml
> chore: updating prod template to remove resources and abstract ones

- .releaserc
- codebuild/release/artifact-hunt.yml
- codebuild/release/release-prod.yml
- codebuild/release/release.yml
- codebuild/release/upload_artifacts.yml
- codebuild/release/version.yml
This PR changes the Release CodeBuild spec based on feedback when running release v1.9.1
> chore: Update release process from release feedback

- codebuild/release/upload_artifacts.yml
- look_4_version.sh
In prep for v2.3.4 release this PR increases the search timeout and uses the correct gh token
> chore: update token name and timeout

- codebuild/release/upload_artifacts.yml
Uses the correct GH PAT in order to log in to github using the gh cli. gh cli is needed in order to create the release and upload the artifacts.
> chore: update gh token

- .releaserc
- README.md
- codebuild/release/artifact-hunt.yml
- codebuild/release/release-prod.yml
- codebuild/release/release.yml
- codebuild/release/upload_artifacts.yml
- codebuild/release/version.yml
- Breaks up release prod into two builds, this way if we need to restart the artifact hunt it won't try to publish again.
- updates README
- uses the correct PAT token in upload artifacts
> chore: update mainline-1.x cd

- README.md
[419](https://github.com/aws/aws-encryption-sdk-java/issues/419)
Updates README get started example to include new methods. Using encryptData and decryptData.
> chore(docs): update README get started example

- codebuild/release/release-prod.yml
- codebuild/release/upload_artifacts.yml
- codebuild/release/validate-prod.yml
Updates release steps to checkout to the latest commit
> chore(ci): change release vars

- codebuild/release/javadoc.yml
YAML tries to parse the colon within a quoted string and causes the last step of the build to fail. Quoting the entire string prevents this condition
> fix(ci): Quote commit statement to prevent errant YAML parsing

- src/main/java/com/amazonaws/encryptionsdk/jce/JceMasterKey.java
> doc: clarify JceMasterKey supported algorithms

- codebuild/ci/release-ci.yml
This PR updates CI to use a different Signing Key that is only used to sign artifacts that get uploaded to CodeArtifact.
> chore: use new signing keys for ci

- README.md
- src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/AwsKmsMrkAwareMasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/RegionalClientSupplier.java
*Issue #, if available:* #834, #829
Corrects the README to state AWS SDK for Java 2.x support.
Updates the JavaDocs for classes that use `KmsClient` interface
to state the `KmsAsyncClient` is not supported.
Closes #834 .
> docs: Detail AWS SDK v2 support

- src/main/java/com/amazonaws/encryptionsdk/CommitmentPolicy.java
*Issue #, if available:* `Detail Commitment Policy on Enum`
*Description of changes:* Detail Commitment Policy on Enum
> docs(CommitmentPolicy): Detail Commitment Policy on Enum

- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
Uses the new signing gpg signing key for release. This key cannot be accessed through CI, since the service role attached to the CI project does not have access to the keys. This secret can only be accessed with appropriate Admin access. 
> chore: use correct signing key for release

- codebuild/ci/release-ci.yml
- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
1.x had not been updated to use the correct signing keys, this pr updates codebuild spec that uses the correct keys
> chore(ci): add correct signing keys for ci and release process

- SUPPORT_POLICY.rst
- src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java
*Issue #, if available:* Mark 1.x as End-of-Support
- Client (AwsCrypto) emits a log warning on creation detailing 1.x is in End-of-Support
- Added the support policy from master
- updated the support policy from master to mark 1.x as End-of-Support.
> chore: Mark 1.x as End-of-Support

- .github/dependabot.yml
We have placed mainline-1.x in EOL, no updates should be added to this branch.
> chore: remove mainline-1.x from dependabot

- README.md
There are two small errors in the example that cause compile errors:
- `.stream` instead of `.stream()`
- `data.getBytes` instead of `plaintext.getBytes`
repro of #1305
> fix: Fix errors in the example code in README.md

- README.md
- pom.xml
-  https://github.com/aws/aws-encryption-sdk-java/issues/1472
- Update `org.bouncycastle` from `bcprov-ext-jdk15on` to `bcprov-ext-jdk18on`
> chore: Update `org.bouncycastle` dependency to artifactId `bcprov-ext-jdk18on`

- pom.xml
*Issue #, if available:* #1669
*Description of changes:* `chore(deps): bump BouncyCastle from 1.72 to 1.75`
> chore(deps): bump BouncyCastle from 1.72 to 1.75

- src/test/java/com/amazonaws/encryptionsdk/jce/KeyStoreProviderTest.java
- Update ESDK Java tests to replace sun.security.* API with supported alternate API
> chore(tests): update ESDK tests to replace sun.security.* API

- cfn/Public-ESDK-Java-CI.yml
- cfn/ci_cd.yml
- update CFN template to pull managed policies from aws-crypto-tools-team+optools-ci@amazon.com(370957321024) for Hierarchical Keyring and KmsRsaKeyring testing.
> chore(CFN): update CFN stack to add managed policies to ci and release role

- .github/workflows/ci.yml
- codebuild/ci/release-ci.yml
- codebuild/ci/validate-ci.yml
- To fix CI, where one of the [Release CI builds is failing](https://github.com/aws/aws-encryption-sdk-java/actions/runs/7082549171/job/19273467501#step:3:240).
- Distinguish between builds triggered by `pull_request` or `push`. Update `release-ci.yml` to not delete CA released while both builds triggered at same time.
> chore: fix release-ci

- cfn/ci_cd.yml
- codebuild/ci/release-ci.yml
- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- pom.xml
- update release role to fetch git submodules
> chore: update release process

- README.md
- pom.xml
- Replace bcprov-ext-jdk18on with bcprov-jdk18on 
> chore: replace bcprov-ext-jdk18on with bcprov-jdk18on

- codebuild/ci/release-ci.yml
- codebuild/ci/vectors-ci.yml
- codebuild/ci/vectors-generator.yml
- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
> chore: update release script

- codebuild/release/version.yml
- `node version >=20.8.1 is required for semantic-release. Found v18.19.0.`
> chore: update node version in version step

- pom.xml
- https://github.com/aws/aws-encryption-sdk-java/issues/1892
_Update dependencies:_
1. `com.amazonaws.aws-java-sdk-kms`: Pull only the KMS module from AWS SDK v1.
2. `org.dafny.DafnyRuntime` and `software.amazon.smithy.dafny.smithy`: Remove the Dafny related dependencies that are already added to the compile and run class paths.
3. `com.github.spotbugs.spotbugs-annotations`: Migrate to [spotbugs dependencies](https://spotbugs.readthedocs.io/en/stable/migration.html).
> chore(pom.xml): update dependencies

- src/main/java/com/amazonaws/encryptionsdk/CryptoResult.java
- src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java
- src/test/java/com/amazonaws/encryptionsdk/AwsCryptoIntegrationTest.java
- deprecate getMasterKeyIds() in CryptoResult and return empty list if keyring is used.
> chore: deprecate getMasterKeyIds() in CryptoResult

- README.md
> chore(README): update README.md

- .gitignore
- src/examples/java/com/amazonaws/crypto/examples/keyrings/CustomizeSDKClient.java
- src/test/java/com/amazonaws/crypto/examples/keyrings/CustomizeSDKClientTest.java
*Issue #, if available:* https://github.com/aws/aws-encryption-sdk-java/issues/1985
- Demonstrate Client Supplier 
> chore(Examples): Customize KMS Client

- .gitmodules
- codebuild/ci/net-vectors-ci.yml
- codebuild/ci/release-ci.yml
- codebuild/ci/vectors-ci-mkp.yml
- codebuild/ci/vectors-ci.yml
- codebuild/ci/vectors-generator.yml
- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- pom.xml
- src/test/java/com/amazonaws/encryptionsdk/TestVectorGenerator.java
- src/test/java/com/amazonaws/encryptionsdk/TestVectorRunner.java
> chore: bump to latest mpl

- src/examples/java/com/amazonaws/crypto/examples/keyrings/hierarchical/SharedCacheAcrossHierarchicalKeyringsExample.java
- src/test/java/com/amazonaws/crypto/examples/keyrings/SharedCacheAcrossHierarchicalKeyringsExampleTest.java
- src/test/java/com/amazonaws/encryptionsdk/AllTestsSuite.java
- src/test/java/com/amazonaws/encryptionsdk/kms/KMSTestFixtures.java
Added an example for shared cache across hierarchical keyrings
> chore(examples): Shared cache across Hierarchical Keyrings

- pom.xml
- src/examples/java/com/amazonaws/crypto/examples/v2/RestrictRegionExample.java
- src/main/java/com/amazonaws/encryptionsdk/kms/AwsKmsMrkAwareMasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/AwsKmsMrkAwareMasterKeyProvider.java
- src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/KmsMasterKeyProvider.java
The AWS SDK for Java's Service Client builders are not thread safe.
Crypto Tools customer's have reported odd,
occasionally disruptive behavior when using them 
in a concurrent setting.
As such, 
Crypto Tools should make it clear how to set a KMS Client
in a thread safe manner.
Which can be done via the Regional Client Supplier.
Additionally, 
we can improve on the Java Documentation to highlight that
Builders are not thread safe,
and that proper Builder suppliers MUST be used,
or customers SHOULD use the alternative client configuration methods.
> chore(JavaDocs): detail thread saftey of SDK Client Builders

- src/test/java/com/amazonaws/encryptionsdk/internal/BlockEncryptionHandlerTest.java
*Issue #, if available:* https://github.com/aws/aws-encryption-sdk-java/issues/2112 (indirectly)
*Description of changes:* See above issue. This PR just adds a similar test to the BlockEncryptionHandler to ensure it doesn't have the same bug. It doesn't, but we'll include the test for robustness's sake. 
> chore: add a test for offset against BlockEncryptionHandler

- cfn/ci_cd.yml
- codebuild/release/release-prod.yml
- codebuild/release/settings.xml
- pom.xml
*Issue #, if available:* n/a
*Description of changes:* The way we publish to Maven is being deprecated. Move to the latest. 
> chore: move release to Nexus Central
